
class LocationJobTitleData {
  static List<String> locations = <String>[
    'Andaman Nicobar Is',
    'Andman & Nicobar Island',
    'Adilabad,Andhra Pradesh',
    'Anantapur,Andhra Pradesh',
    'Chittoor,Andhra Pradesh',
    'East Godavari,Andhra Pradesh',
    'Guntur,Andhra Pradesh',
    'Hyderabad,Andhra Pradesh',
    'Kadapa,Andhra Pradesh',
    'Karimnagar,Andhra Pradesh',
    'Khammam/Bhadrachalam,Andhra Pradesh',
    'Krishna,Andhra Pradesh',
    'Kurnool,Andhra Pradesh',
    'Mahbubnagar,Andhra Pradesh',
    'Medak,Andhra Pradesh',
    'Nalgonda,Andhra Pradesh',
    'Nellore,Andhra Pradesh',
    'Nizamabad,Andhra Pradesh',
    'Prakasam,Andhra Pradesh',
    'Rangareddi,Andhra Pradesh',
    'Srikakulam,Andhra Pradesh',
    'Visakhapatnam,Andhra Pradesh',
    'Vizianagaram,Andhra Pradesh',
    'Warangal,Andhra Pradesh',
    'West Godavari,Andhra Pradesh',
    'Anjaw,Arunachal Pradesh',
    'Changlang,Arunachal Pradesh',
    'East Kameng,Arunachal Pradesh',
    'East Siang,Arunachal Pradesh',
    'Kurung Kumey,Arunachal Pradesh',
    'Lohit,Arunachal Pradesh',
    'Lower Dibang Valley,Arunachal Pradesh',
    'Lower Subansiri,Arunachal Pradesh',
    'Papum Pare,Arunachal Pradesh',
    'Tawang,Arunachal Pradesh',
    'Tirap,Arunachal Pradesh',
    'Upper Dibang Valley,Arunachal Pradesh',
    'Upper Siang,Arunachal Pradesh',
    'Upper Subansiri,Arunachal Pradesh',
    'West Kameng,Arunachal Pradesh',
    'West Siang,Arunachal Pradesh',
    'Baksa,Assam',
    'Barpeta,Assam',
    'Bongaigaon,Assam',
    'Cachar,Assam',
    'Chirang,Assam',
    'Darrang,Assam',
    'Dhemaji,Assam',
    'Dhubri,Assam',
    'Dibrugarh,Assam',
    'Goalpara,Assam',
    'Golaghat,Assam',
    'Hailakandi,Assam',
    'Jorhat,Assam',
    'Kamrup,Assam',
    'Karbi Anglong,Assam',
    'Karimganj,Assam',
    'Kokrajhar,Assam',
    'Lakhimpur,Assam',
    'Marigaon,Assam',
    'Nagaon,Assam',
    'Nalbari,Assam',
    'North Cachar Hills,Assam',
    'Sibsagar,Assam',
    'Sonitpur,Assam',
    'Tinsukia,Assam',
    'Udalguri,Assam',
    'Araria,Bihar',
    'Arwal,Bihar',
    'Aurangabad-Bi,Bihar',
    'Banka,Bihar',
    'Begusarai,Bihar',
    'Bhagalpur,Bihar',
    'Bhojpur,Bihar',
    'Buxar,Bihar',
    'Darbhanga,Bihar',
    'East Champaran,Bihar',
    'Gaya,Bihar',
    'Gopalganj,Bihar',
    'Jamui,Bihar',
    'Jehanabad,Bihar',
    'Kaimur,Bihar',
    'Katihar,Bihar',
    'Khagaria,Bihar',
    'Kishanganj,Bihar',
    'Lakhisarai,Bihar',
    'Madhepura,Bihar',
    'Madhubani,Bihar',
    'Munger,Bihar',
    'Muzaffarpur,Bihar',
    'Nalanda,Bihar',
    'Nawada,Bihar',
    'Patna,Bihar',
    'Purnia,Bihar',
    'Rohtas,Bihar',
    'Saharsa,Bihar',
    'Samastipur,Bihar',
    'Saran,Bihar',
    'Sheikhpura,Bihar',
    'Sheohar,Bihar',
    'Sitamarhi,Bihar',
    'Siwan,Bihar',
    'Supaul,Bihar',
    'Vaishali,Bihar',
    'West Champaran,Bihar',
    'Bastar,Chattisgarh',
    'Bilaspur-Cg,Chattisgarh',
    'Dantewada,Chattisgarh',
    'Dhamtari,Chattisgarh',
    'Durg,Chattisgarh',
    'Janjgir,Chattisgarh',
    'Jashpur,Chattisgarh',
    'Kanker,Chattisgarh',
    'Kawardha/Kabir Dham,Chattisgarh',
    'Korba,Chattisgarh',
    'Koriya,Chattisgarh',
    'Mahasamund,Chattisgarh',
    'Raigarh-Cg,Chattisgarh',
    'Raipur,Chattisgarh',
    'Rajnandgaon,Chattisgarh',
    'Surguja (Ambikapur),Chattisgarh',
    'Chandigarh,Chandigarh',
    'Daman,Daman & Diu',
    'Diu,Daman & Diu',
    'Central,Delhi',
    'City Zone,Delhi',
    'Civili Line,Delhi',
    'Karol Bagh,Delhi',
    'Najafgarh,Delhi',
    'Narela,Delhi',
    'Rohini,Delhi',
    'S. Pahar Ganj,Delhi',
    'Shahadra (N),Delhi',
    'Shahadra (S),Delhi',
    'South,Delhi',
    'West,Delhi',
    'Dadra & Nagar Haveli,Dadar & Nagar Havali',
    'Goa,Goa',
    'Ahmedabad,Gujarat',
    'Amreli,Gujarat',
    'Anand,Gujarat',
    'Banaskantha,Gujarat',
    'Bharuch,Gujarat',
    'Bhavnagar,Gujarat',
    'Dahod,Gujarat',
    'Dang,Gujarat',
    'Gandhinagar,Gujarat',
    'Godhara,Gujarat',
    'Jamnagar,Gujarat',
    'Junagadh,Gujarat',
    'Kheda,Gujarat',
    'Kutch,Gujarat',
    'Mehsana,Gujarat',
    'Narmada,Gujarat',
    'Navsari,Gujarat',
    'Panchmahals,Gujarat',
    'Patan,Gujarat',
    'Porbandar,Gujarat',
    'Rajkot,Gujarat',
    'Sabarkantha,Gujarat',
    'Surat,Gujarat',
    'Surendranagar,Gujarat',
    'Tapi,Gujarat',
    'Vadodara,Gujarat',
    'Valsad,Gujarat',
    'Ambala,Haryana',
    'Bhiwani,Haryana',
    'Faridabad,Haryana',
    'Fatehabad,Haryana',
    'Gurgaon,Haryana',
    'Hisar,Haryana',
    'Jhajjar,Haryana',
    'Jind,Haryana',
    'Kaithal,Haryana',
    'Karnal,Haryana',
    'Kurukshetra,Haryana',
    'Mahendragarh,Haryana',
    'Panchkula,Haryana',
    'Panipat,Haryana',
    'Rewari,Haryana',
    'Rohtak,Haryana',
    'Sirsa,Haryana',
    'Sonepat,Haryana',
    'Yamunanagar,Haryana',
    'Bilaspur,Himachal Pradesh',
    'Chamba,Himachal Pradesh',
    'Hamirpur,Himachal Pradesh',
    'Kangra,Himachal Pradesh',
    'Kinnaur,Himachal Pradesh',
    'Kullu,Himachal Pradesh',
    'Lahaul & Spiti,Himachal Pradesh',
    'Mandi,Himachal Pradesh',
    'Shimla,Himachal Pradesh',
    'Sirmaur,Himachal Pradesh',
    'Solan,Himachal Pradesh',
    'Una,Himachal Pradesh',
    'Anantnag,Jammu & Kashmir',
    'Badgam,Jammu & Kashmir',
    'Bandipora,Jammu & Kashmir',
    'Baramula,Jammu & Kashmir',
    'Doda,Jammu & Kashmir',
    'Ganderbal,Jammu & Kashmir',
    'Jammu,Jammu & Kashmir',
    'Kargil,Jammu & Kashmir',
    'Kathua,Jammu & Kashmir',
    'Kishtwar,Jammu & Kashmir',
    'Kupwara,Jammu & Kashmir',
    'Leh,Jammu & Kashmir',
    'Poonch,Jammu & Kashmir',
    'Pulwama,Jammu & Kashmir',
    'Rajouri,Jammu & Kashmir',
    'Ramban,Jammu & Kashmir',
    'Reasi,Jammu & Kashmir',
    'Samba,Jammu & Kashmir',
    'Shopian,Jammu & Kashmir',
    'Srinagar,Jammu & Kashmir',
    'Udhampur,Jammu & Kashmir',
    'Bokaro,Jharkhand',
    'Chatra,Jharkhand',
    'Deoghar,Jharkhand',
    'Dhanbad,Jharkhand',
    'Dumka,Jharkhand',
    'East Singhbhum,Jharkhand',
    'Garhwa,Jharkhand',
    'Giridih,Jharkhand',
    'Godda,Jharkhand',
    'Gumla,Jharkhand',
    'Hazaribagh,Jharkhand',
    'Jamtara,Jharkhand',
    'Khunti,Jharkhand',
    'Koderma,Jharkhand',
    'Latehar,Jharkhand',
    'Lohardaga,Jharkhand',
    'Pakur,Jharkhand',
    'Palamau,Jharkhand',
    'Ramgarh,Jharkhand',
    'Ranchi,Jharkhand',
    'Sahibganj,Jharkhand',
    'Seraikela-Kharsawan,Jharkhand',
    'Simdega,Jharkhand',
    'West Singhbhum,Jharkhand',
    'Bagalkot,Karnataka',
    'Bangalore,Karnataka',
    'Bangalore Rural,Karnataka',
    'Belgaum,Karnataka',
    'Bellary,Karnataka',
    'Bidar,Karnataka',
    'Bijapur,Karnataka',
    'Chamrajanagar,Karnataka',
    'Chikballapur,Karnataka',
    'Chikkamagaluru,Karnataka',
    'Chitradurga,Karnataka',
    'Dakshin Kannada,Karnataka',
    'Davanagere,Karnataka',
    'Dharwad,Karnataka',
    'Gadag,Karnataka',
    'Gulbarga,Karnataka',
    'Hassan,Karnataka',
    'Haveri,Karnataka',
    'Kodagu,Karnataka',
    'Kolar,Karnataka',
    'Koppal,Karnataka',
    'Mandya,Karnataka',
    'Mysore,Karnataka',
    'Raichur,Karnataka',
    'Ramanagara,Karnataka',
    'Shimoga,Karnataka',
    'Tumkur,Karnataka',
    'Udupi,Karnataka',
    'Uttara Kannada,Karnataka',
    'Vijayapura,Karnataka',
    'Yadgir,Karnataka',
    'Alappuzha,Kerala',
    'Ernakulam,Kerala',
    'Idukki,Kerala',
    'Kannur,Kerala',
    'Kasaragod,Kerala',
    'Kollam,Kerala',
    'Kottayam,Kerala',
    'Kozhikode,Kerala',
    'Malappuram,Kerala',
    'Palakkad,Kerala',
    'Pathanamthitta,Kerala',
    'Thiruvananthapuram,Kerala',
    'Thrissur,Kerala',
    'Wayanad,Kerala',
    'Ahmednagar,Maharashtra',
    'Akola,Maharashtra',
    'Amravati,Maharashtra',
    'Aurangabad-Mh,Maharashtra',
    'Beed,Maharashtra',
    'Bhandara,Maharashtra',
    'Buldhana,Maharashtra',
    'Chandrapur,Maharashtra',
    'Dhule,Maharashtra',
    'Gadchiroli,Maharashtra',
    'Gondia,Maharashtra',
    'Hingoli,Maharashtra',
    'Jalgaon,Maharashtra',
    'Jalna,Maharashtra',
    'Kolhapur,Maharashtra',
    'Latur,Maharashtra',
    'Mumbai,Maharashtra',
    'Mumbai Suburban,Maharashtra',
    'Nagpur,Maharashtra',
    'Nanded,Maharashtra',
    'Nandurbar,Maharashtra',
    'Nashik,Maharashtra',
    'Osmanabad,Maharashtra',
    'Palghar,Maharashtra',
    'Parbhani,Maharashtra',
    'Pune,Maharashtra',
    'Raigad,Maharashtra',
    'Ratnagiri,Maharashtra',
    'Sangli,Maharashtra',
    'Satara,Maharashtra',
    'Sindhudurg,Maharashtra',
    'Solapur,Maharashtra',
    'Thane,Maharashtra',
    'Wardha,Maharashtra',
    'Washim,Maharashtra',
    'Yavatmal,Maharashtra',
    'Bishnupur,Manipur',
    'Chandel,Manipur',
    'Churachandpur,Manipur',
    'Imphal East,Manipur',
    'Imphal West,Manipur',
    'Senapati,Manipur',
    'Tamenglong,Manipur',
    'Thoubal,Manipur',
    'Ukhrul,Manipur',
    'East Garo Hills,Meghalaya',
    'East Khasi Hills,Meghalaya',
    'Jaintia Hills,Meghalaya',
    'Ri-Bhoi,Meghalaya',
    'South Garo Hills,Meghalaya',
    'West Garo Hills,Meghalaya',
    'West Khasi Hills,Meghalaya',
    'Aizawl,Mizoram',
    'Champhai,Mizoram',
    'Kolasib,Mizoram',
    'Lawngtlai,Mizoram',
    'Lunglei,Mizoram',
    'Mamit,Mizoram',
    'Saiha,Mizoram',
    'Serchhip,Mizoram',
    'Dimapur,Nagaland',
    'Kiphire,Nagaland',
    'Kohima,Nagaland',
    'Longleng,Nagaland',
    'Mokokchung,Nagaland',
    'Mon,Nagaland',
    'Peren,Nagaland',
    'Phek,Nagaland',
    'Tuensang,Nagaland',
    'Wokha,Nagaland',
    'Zunheboto,Nagaland',
    'Angul,Orissa',
    'Balangir,Orissa',
    'Balasore,Orissa',
    'Bargarh,Orissa',
    'Bhadrak,Orissa',
    'Boudh,Orissa',
    'Cuttack,Orissa',
    'Deogarh,Orissa',
    'Dhenkanal,Orissa',
    'Gajapati,Orissa',
    'Ganjam,Orissa',
    'Jagatsinghapur,Orissa',
    'Jajpur,Orissa',
    'Jharsuguda,Orissa',
    'Kalahandi,Orissa',
    'Kandhamal,Orissa',
    'Kendrapara,Orissa',
    'Kendujhar,Orissa',
    'Khurda,Orissa',
    'Koraput,Orissa',
    'Malkangiri,Orissa',
    'Mayurbhanj,Orissa',
    'Nabarangpur,Orissa',
    'Nayagarh,Orissa',
    'Nuapada,Orissa',
    'Puri,Orissa',
    'Rayagada,Orissa',
    'Sambalpur,Orissa',
    'Subarnapur,Orissa',
    'Sundergarh,Orissa',
    'Amritsar,Punjab',
    'Barnala,Punjab',
    'Bathinda,Punjab',
    'Faridkot,Punjab',
    'Fatehgarh Sahib,Punjab',
    'Fazilka,Punjab',
    'Ferozepur,Punjab',
    'Gurdaspur,Punjab',
    'Hoshiarpur,Punjab',
    'Jalandhar,Punjab',
    'Kapurthala,Punjab',
    'Ludhiana,Punjab',
    'Mansa,Punjab',
    'Moga,Punjab',
    'Muktsar,Punjab',
    'Nawanshahr,Punjab',
    'Patiala,Punjab',
    'Rupnagar,Punjab',
    'S.A.S Nagar,Punjab',
    'Sangrur,Punjab',
    'Tarn Taran,Punjab',
    'Ajmer,Rajasthan',
    'Alwar,Rajasthan',
    'Banswara,Rajasthan',
    'Baran,Rajasthan',
    'Barmer,Rajasthan',
    'Bharatpur,Rajasthan',
    'Bhilwara,Rajasthan',
    'Bikaner,Rajasthan',
    'Bundi,Rajasthan',
    'Chittaurgarh,Rajasthan',
    'Churu,Rajasthan',
    'Dausa,Rajasthan',
    'Dholpur,Rajasthan',
    'Dungarpur,Rajasthan',
    'Ganganagar,Rajasthan',
    'Hanumangarh,Rajasthan',
    'Jaipur,Rajasthan',
    'Jaisalmer,Rajasthan',
    'Jalore,Rajasthan',
    'Jhalawar,Rajasthan',
    'Jhunjhunu,Rajasthan',
    'Jodhpur,Rajasthan',
    'Karauli,Rajasthan',
    'Kota,Rajasthan',
    'Nagaur,Rajasthan',
    'Pali,Rajasthan',
    'Pratapgarh,Rajasthan',
    'Rajsamand,Rajasthan',
    'Sawai Madhopur,Rajasthan',
    'Sikar,Rajasthan',
    'Sirohi,Rajasthan',
    'Tonk,Rajasthan',
    'Udaipur,Rajasthan',
    'East,Sikkim',
    'North,Sikkim',
    'South,Sikkim',
    'West,Sikkim',
    'Ariyalur,Tamil Nadu',
    'Chennai,Tamil Nadu',
    'Coimbatore,Tamil Nadu',
    'Cuddalore,Tamil Nadu',
    'Dharmapuri,Tamil Nadu',
    'Dindigul,Tamil Nadu',
    'Erode,Tamil Nadu',
    'Kanchipuram,Tamil Nadu',
    'Kanyakumari,Tamil Nadu',
    'Karur,Tamil Nadu',
    'Krishnagiri,Tamil Nadu',
    'Madurai,Tamil Nadu',
    'Nagapattinam,Tamil Nadu',
    'Namakkal,Tamil Nadu',
    'Nilgiris,Tamil Nadu',
    'Perambalur,Tamil Nadu',
    'Pudukkottai,Tamil Nadu',
    'Ramanathapuram,Tamil Nadu',
    'Salem,Tamil Nadu',
    'Sivaganga,Tamil Nadu',
    'Thanjavur,Tamil Nadu',
    'Theni,Tamil Nadu',
    'Thoothukudi,Tamil Nadu',
    'Tiruchirapalli,Tamil Nadu',
    'Tirunelveli,Tamil Nadu',
    'Tiruvallur,Tamil Nadu',
    'Tiruvannamalai,Tamil Nadu',
    'Tiruvarur,Tamil Nadu',
    'Vellore,Tamil Nadu',
    'Viluppuram,Tamil Nadu',
    'Virudhunagar,Tamil Nadu',
    'Adilabad,Telangana',
    'Bhadradri Kothagudem,Telangana',
    'Hyderabad,Telangana',
    'Jagtial,Telangana',
    'Jangaon,Telangana',
    'Jayashankar Bhupalpally,Telangana',
    'Jogulamba Gadwal,Telangana',
    'Kamareddy,Telangana',
    'Karimnagar,Telangana',
    'Khammam,Telangana',
    'Komaram Bheem/Talamadugu,Telangana',
    'Mahabubabad,Telangana',
    'Mahabubnagar,Telangana',
    'Mancherial,Telangana',
    'Medak,Telangana',
    'Medchal,Telangana',
    'Mulugu,Telangana',
    'Nagarkurnool,Telangana',
    'Nalgonda,Telangana',
    'Narayanpet,Telangana',
    'Nirmal,Telangana',
    'Nizamabad,Telangana',
    'Peddapalli,Telangana',
    'Rajanna Sircilla,Telangana',
    'Ranga Reddy,Telangana',
    'Sangareddy,Telangana',
    'Siddipet,Telangana',
    'Suryapet,Telangana',
    'Vikarabad,Telangana',
    'Wanaparthy,Telangana',
    'Warangal Rural,Telangana',
    'Warangal Urban,Telangana',
    'Yadadri Bhuvanagiri,Telangana',
    'Dhalai,Tripura',
    'Gomati,Tripura',
    'Khowai,Tripura',
    'North Tripura,Tripura',
    'Sipahijala,Tripura',
    'South Tripura,Tripura',
    'Unakoti,Tripura',
    'West Tripura,Tripura',
    'Agra,Uttar Pradesh',
    'Aligarh,Uttar Pradesh',
    'Allahabad,Uttar Pradesh',
    'Ambedkar Nagar,Uttar Pradesh',
    'Amethi (Chatrapati Sahuji Mahraj Nagar),Uttar Pradesh',
    'Amroha,Uttar Pradesh',
    'Auraiya,Uttar Pradesh',
    'Azamgarh,Uttar Pradesh',
    'Baghpat,Uttar Pradesh',
    'Bahraich,Uttar Pradesh',
    'Ballia,Uttar Pradesh',
    'Balrampur,Uttar Pradesh',
    'Banda,Uttar Pradesh',
    'Barabanki,Uttar Pradesh',
    'Bareilly,Uttar Pradesh',
    'Basti,Uttar Pradesh',
    'Bhadohi,Uttar Pradesh',
    'Bijnor,Uttar Pradesh',
    'Budaun,Uttar Pradesh',
    'Bulandshahr,Uttar Pradesh',
    'Chandauli,Uttar Pradesh',
    'Chitrakoot,Uttar Pradesh',
    'Deoria,Uttar Pradesh',
    'Etah,Uttar Pradesh',
    'Etawah,Uttar Pradesh',
    'Farrukhabad,Uttar Pradesh',
    'Fatehpur,Uttar Pradesh',
    'Firozabad,Uttar Pradesh',
    'Gautam Buddha Nagar,Uttar Pradesh',
    'Ghaziabad,Uttar Pradesh',
    'Ghazipur,Uttar Pradesh',
    'Gonda,Uttar Pradesh',
    'Gorakhpur,Uttar Pradesh',
    'Hamirpur-Up,Uttar Pradesh',
    'Hapur,Uttar Pradesh',
    'Hardoi,Uttar Pradesh',
    'Hathras,Uttar Pradesh',
    'Jalaun,Uttar Pradesh',
    'Jaunpur,Uttar Pradesh',
    'Jhansi,Uttar Pradesh',
    'Kannauj,Uttar Pradesh',
    'Kanpur Dehat (Ramabai Nagar),Uttar Pradesh',
    'Kanpur Nagar,Uttar Pradesh',
    'Kanshiram Nagar (Kasganj),Uttar Pradesh',
    'Kaushambi,Uttar Pradesh',
    'Kushinagar (Padrauna),Uttar Pradesh',
    'Lakhimpur - Kheri,Uttar Pradesh',
    'Lalitpur,Uttar Pradesh',
    'Lucknow,Uttar Pradesh',
    'Maharajganj,Uttar Pradesh',
    'Mahoba,Uttar Pradesh',
    'Mainpuri,Uttar Pradesh',
    'Mathura,Uttar Pradesh',
    'Mau,Uttar Pradesh',
    'Meerut,Uttar Pradesh',
    'Mirzapur,Uttar Pradesh',
    'Moradabad,Uttar Pradesh',
    'Muzaffarnagar,Uttar Pradesh',
    'Pilibhit,Uttar Pradesh',
    'Pratapgarh,Uttar Pradesh',
    'Prayagraj,Uttar Pradesh',
    'Raebareli,Uttar Pradesh',
    'Rampur,Uttar Pradesh',
    'Saharanpur,Uttar Pradesh',
    'Sambhal,Uttar Pradesh',
    'Sant Kabir Nagar,Uttar Pradesh',
    'Shahjahanpur,Uttar Pradesh',
    'Shamali (Prabuddh Nagar),Uttar Pradesh',
    'Shravasti,Uttar Pradesh',
    'Siddharth Nagar,Uttar Pradesh',
    'Sitapur,Uttar Pradesh',
    'Sonbhadra,Uttar Pradesh',
    'Sultanpur,Uttar Pradesh',
    'Unnao,Uttar Pradesh',
    'Varanasi,Uttar Pradesh',
    'Almora,Uttarakhand',
    'Bageshwar,Uttarakhand',
    'Chamoli,Uttarakhand',
    'Champawat,Uttarakhand',
    'Dehradun,Uttarakhand',
    'Haridwar,Uttarakhand',
    'Nainital,Uttarakhand',
    'Pauri Garhwal,Uttarakhand',
    'Pithoragarh,Uttarakhand',
    'Rudraprayag,Uttarakhand',
    'Tehri Garhwal,Uttarakhand',
    'Udham Singh Nagar,Uttarakhand',
    'Uttarkashi,Uttarakhand',
    'Alipurduar,West Bengal',
    'Bankura,West Bengal',
    'Birbhum,West Bengal',
    'Cooch Behar,West Bengal',
    'Dakshin Dinajpur (South Dinajpur),West Bengal',
    'Darjeeling,West Bengal',
    'Hooghly,West Bengal',
    'Howrah,West Bengal',
    'Jalpaiguri,West Bengal',
    'Jhargram,West Bengal',
    'Kalimpong,West Bengal',
    'Kolkata,West Bengal',
    'Malda,West Bengal',
    'Murshidabad,West Bengal',
    'Nadia,West Bengal',
    'North 24 Parganas,West Bengal',
    'Paschim Bardhaman (West Bardhaman),West Bengal',
    'Paschim Medinipur (West Medinipur),West Bengal',
    'Purba Bardhaman (East Bardhaman),West Bengal',
    'Purba Medinipur (East Medinipur),West Bengal',
    'Purulia,West Bengal',
    'South 24 Parganas,West Bengal',
    'Uttar Dinajpur (North Dinajpur),West Bengal',
  ];

  static List<String> jobTitles =<String> [
    'Software Engineer',
    'Web Developer',
    'Mobile App Developer',
    'Frontend Developer',
    'Backend Developer',
    'Full-stack Developer',
    'Java Developer',
    'Python Developer',
    'JavaScript Developer',
    'Ruby on Rails Developer',
    'PHP Developer',
    'C++ Developer',
    'C# Developer',
    'Swift Developer',
    'Kotlin Developer',
    'Flutter Developer',
    'React Native Developer',
    'Angular Developer',
    'Vue.js Developer',
    'Node.js Developer',
    'Express.js Developer',
    'Django Developer',
    'Flask Developer',
    'Laravel Developer',
    'Spring Developer',
    'Hibernate Developer',
    'ASP.NET Developer',
    'Unity Developer',
    'Unreal Engine Developer',
    'Game Developer',
    'UI/UX Designer',
    'Graphic Designer',
    'Visual Designer',
    'Interaction Designer',
    'Product Designer',
    'User Researcher',
    'Data Scientist',
    'Data Analyst',
    'Machine Learning Engineer',
    'AI Engineer',
    'Computer Vision Engineer',
    'Natural Language Processing Engineer',
    'Big Data Engineer',
    'Cloud Engineer',
    'DevOps Engineer',
    'Site Reliability Engineer',
    'Systems Engineer',
    'Network Engineer',
    'Security Engineer',
    'IT Support Specialist',
    'Technical Writer',
    'QA Engineer',
    'Automation Test Engineer',
    'Manual Test Engineer',
    'Performance Test Engineer',
    'Embedded Systems Engineer',
    'IoT Developer',
    'Robotics Engineer',
    'AR/VR Developer',
    'Blockchain Developer',
    'Cryptocurrency Developer',
    'Smart Contract Developer',
    'Cybersecurity Analyst',
    'Penetration Tester',
    'Incident Responder',
    'SOC Analyst',
    'Threat Intelligence Analyst',
    'Security Architect',
    'Network Administrator',
    'Database Administrator',
    'Systems Administrator',
    'IT Manager',
    'Project Manager',
    'Scrum Master',
    'Product Manager',
    'Technical Lead',
    'Engineering Manager',
    'Director of Engineering',
    'Chief Technology Officer (CTO)',
    'Chief Information Officer (CIO)',
    'Chief Information Security Officer (CISO)',
    'Chief Data Officer (CDO)',
    'Business Analyst',
    'Systems Analyst',
    'IT Consultant',
    'Solutions Architect',
    'Enterprise Architect',
    'IT Auditor',
    'Compliance Analyst',
    'Risk Analyst',
    'IT Trainer',
    'Technical Recruiter',
    'Talent Acquisition Specialist',
    'HR Business Partner',
    'People Operations Manager',
    'Diversity and Inclusion Specialist',
    'Employee Relations Manager',
    'Compensation and Benefits Analyst',
    'Organizational Development Specialist',
    'Learning and Development Manager',
    'Finance Analyst',
    'Accounting Specialist',
    'Financial Controller',
    'Budget Analyst',
    'Financial Planning and Analysis Manager',
    'Treasury Analyst',
    'Tax Specialist',
    'Auditor',
    'Business Intelligence Analyst',
    'Data Warehouse Developer',
    'ETL Developer',
    'Business Analytics Manager',
    'Marketing Analyst',
    'SEO Specialist',
    'SEM Specialist',
    'Content Strategist',
    'Digital Marketing Manager',
    'Social Media Manager',
    'Email Marketing Specialist',
    'Growth Hacker',
    'Sales Representative',
    'Account Manager',
    'Business Development Manager',
    'Sales Engineer',
    'Customer Success Manager',
    'Technical Account Manager',
    'Account Executive',
    'Sales Operations Analyst',
    'Channel Manager',
    'Product Marketing Manager',
    'Brand Manager',
    'Marketing Communications Manager',
    'Public Relations Specialist',
    'Event Coordinator',
    'Community Manager',
    'Content Creator',
    'Influencer Marketing Manager',
    'UX Researcher',
    'Conversion Rate Optimizer',
    'CRM Specialist',
    'Customer Support Specialist',
    'Technical Support Engineer',
    'Help Desk Technician',
    'Customer Experience Manager',
    'Service Desk Analyst',
    'IT Service Delivery Manager',
    'ServiceNow Developer',
    'ITIL Specialist',
    'Change Manager',
    'Release Manager',
    'Incident Manager',
    'Problem Manager',
    'Access Management Specialist',
    'Identity and Access Management Engineer',
    'Network Security Engineer',
    'Endpoint Security Engineer',
    'Security Operations Center (SOC) Manager',
    'SIEM Engineer',
    'Threat Hunter',
    'Cybersecurity Consultant',
    'Data Privacy Specialist',
    'Compliance Manager',
    'Legal Counsel',
    'Intellectual Property Lawyer',
    'Contract Manager',
    'Procurement Specialist',
    'Vendor Manager',
    'Supply Chain Analyst',
    'Logistics Coordinator',
    'Inventory Manager',
    'Warehouse Supervisor',
    'Demand Planner',
    'Supply Chain Manager',
    'Procurement Director',
    'Operations Analyst',
    'Process Improvement Specialist',
    'Lean Six Sigma Black Belt',
    'Continuous Improvement Manager',
    'Quality Assurance Manager',
    'Supplier Quality Engineer',
    'Manufacturing Engineer',
    'Production Planner',
    'Operations Manager',
    'Plant Manager',
    'General Manager',
    'Regional Manager',
    'VP of Operations',
    'Chief Operating Officer (COO)',
    'Strategic Planner',
    'Management Consultant',
    'Business Process Analyst',
    'Business Transformation Manager',
    'Change Management Consultant',
    'Organizational Change Manager',
    'Leadership Development Specialist',
    'Executive Coach',
    'Corporate Trainer',
    'Learning Experience Designer',
    'HR Transformation Consultant',
    'Diversity, Equity, and Inclusion (DEI) Director',
  ];

}
